# Generated by Django 6.0.4 on 2026-09-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(default='Xe máy số', max_length=50)),
                ('issue_type', models.CharField(default='Thủng săm / xẹp lốp', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('location_address', models.CharField(default='120 Hoàng Minh Thảo, Liên Chiểu, Đà Nẵng', max_length=255)),
                ('latitude', models.FloatField(default=16.0725)),
                ('longitude', models.FloatField(default=108.152)),
                ('proposed_fee', models.CharField(default='50.000 VNĐ', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Đang tìm người hỗ trợ'), ('ACCEPTED', 'Đã tiếp nhận'), ('IN_PROGRESS', 'Đang di chuyển tới'), ('ARRIVED', 'Đã tới nơi'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_rescues', to=settings.AUTH_USER_MODEL)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('NEW_REQUEST', 'Yêu cầu cứu hộ mới'), ('ACCEPTED', 'Yêu cầu đã được tiếp nhận'), ('REJECTED', 'Người hỗ trợ từ chối'), ('STATUS_UPDATE', 'Cập nhật trạng thái'), ('CHAT', 'Tin nhắn mới')], default='NEW_REQUEST', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('rescue_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rescuerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.rescuerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RescueResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('NOTIFIED', 'Gửi thông báo'), ('VIEWED', 'Đã xem chi tiết'), ('ACCEPTED', 'Chấp nhận hỗ trợ'), ('REJECTED', 'Từ chối hỗ trợ')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='core.rescuerequest')),
                ('rescuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VICTIM', 'Người gặp nạn'), ('RESCUER', 'Người cứu hộ / Thợ'), ('BOTH', 'Cả hai vai trò')], default='BOTH', max_length=20)),
                ('phone', models.CharField(default='0905123456', max_length=20)),
                ('avatar_url', models.CharField(default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80', max_length=255)),
                ('rescuer_status', models.CharField(choices=[('READY', 'Sẵn sàng hỗ trợ'), ('BUSY', 'Đang hỗ trợ'), ('OFFLINE', 'Tạm nghỉ / Ngoại tuyến')], default='READY', max_length=20)),
                ('vehicle_type', models.CharField(default='Honda Wave Alpha', max_length=50)),
                ('vehicle_plate', models.CharField(default='43-C1 123.45', max_length=20)),
                ('current_latitude', models.FloatField(default=16.0748)),
                ('current_longitude', models.FloatField(default=108.1499)),
                ('rating_avg', models.FloatField(default=4.9)),
                ('total_rescues', models.IntegerField(default=12)),
                ('bio', models.TextField(blank=True, default='Thợ sửa xe máy lưu động 24/7, vá săm, thay ruột, kích bình ắc quy.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
