# Generated by Django 6.1.1 on 2026-09-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Số CCCD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
