# Generated by Django 6.0.4 on 2026-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_receiver_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuerequest',
            name='proposed_fee',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
